name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

  merge_to_main:
    name: Merge to Main
    needs: build_and_test
    runs-on: ubuntu-latest
    if: ${{ needs.build_and_test.result == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge changes to main
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'youremail@example.com'
        git checkout main
        git merge develop --no-ff --no-edit
        git push origin main
